import { Resort } from './types';

export const RESORTS: Resort[] = [
  {
    id: 'resort-0',
    name: "OBLU Select Lobigili",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/OBLUSelectLobigili/600/400`,
    q_despreocupacion: ["A"],
    q5: ["B","C"],
    q1: ["A"],
    q2: ["A"],
    q3: ["A","B"],
    q4: ["A","B"],
    'q4.1': ["A","B"],
    'q4.2': ["C"],
    q9: ["B","C"],
    q11: ["A","D"],
    q_priorities: ["B", "D", "F", "G"]
  },
  {
    id: 'resort-1',
    name: "Emerald Faarufushi Resort & Spa",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/EmeraldFaarufushiResort&Spa/600/400`,
    q_despreocupacion: ["A"],
    q5: ["B","C"],
    q1: ["A"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A"],
    'q4.1': ["A"],
    'q4.2': [],
    q9: ["B","C"],
    q11: ["B","D"],
    q_priorities: ["A", "B", "D", "G"]
  },
  {
    id: 'resort-2',
    name: "OBLU Nature Helengeli",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/OBLUNatureHelengeli/600/400`,
    q_despreocupacion: ["A"],
    q5: ["B","C"],
    q1: ["A"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A"],
    'q4.1': ["A"],
    'q4.2': [],
    q9: ["B","C"],
    q11: ["A","D"],
    q_priorities: ["A", "B", "D", "G"]
  },
  {
    id: 'resort-3',
    name: "Veligandu Maldives",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/VeliganduMaldives/600/400`,
    q_despreocupacion: ["A"],
    q5: ["B","C"],
    q1: ["A"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A","B"],
    'q4.1': ["A","B"],
    'q4.2': ["B","A"],
    q9: ["B","C"],
    q11: ["B","D"],
    q_priorities: ["A", "B", "D", "F", "G"]
  },
  {
    id: 'resort-4',
    name: "VARU by Atmosphere",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/VARUbyAtmosphere/600/400`,
    q_despreocupacion: ["A"],
    q5: ["B","C"],
    q1: ["A"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A","B"],
    'q4.1': ["A","B"],
    'q4.2': ["C"],
    q9: ["B","C"],
    q11: ["A","D"],
    q_priorities: ["A", "B", "D", "F", "G"]
  },
  {
    id: 'resort-5',
    name: "OBLU Select Sangeli",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/OBLUSelectSangeli/600/400`,
    q_despreocupacion: ["A"],
    q5: ["B","C"],
    q1: ["B"],
    q2: ["A"],
    q3: ["A","B","C"],
    q4: ["A"],
    'q4.1': ["A"],
    'q4.2': [],
    q9: ["B","C"],
    q11: ["A","D"],
    q_priorities: ["A", "B", "G"]
  },
  {
    id: 'resort-6',
    name: "OZEN Life Maadhoo",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/OZENLifeMaadhoo/600/400`,
    q_despreocupacion: ["A"],
    q5: ["A","B","C"],
    q1: ["B"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A"],
    'q4.1': ["A"],
    'q4.2': [],
    q9: ["A","C"],
    q11: ["A","D"],
    q_priorities: ["A", "B", "C", "H"]
  },
  {
    id: 'resort-7',
    name: "RAAYA by Atmosphere",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/RAAYAbyAtmosphere/600/400`,
    q_despreocupacion: ["A"],
    q5: ["B","C"],
    q1: ["B"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A"],
    'q4.1': ["A"],
    'q4.2': [],
    q9: ["B","C"],
    q11: ["B","D"],
    q_priorities: ["A", "B", "G"]
  },
  {
    id: 'resort-8',
    name: "Atmosphere Kanifushi",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/AtmosphereKanifushi/600/400`,
    q_despreocupacion: ["A"],
    q5: ["B","C"],
    q1: ["B"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A"],
    'q4.1': ["A"],
    'q4.2': [],
    q9: ["A","B","C"],
    q11: ["B","D"],
    q_priorities: ["A", "B", "G", "H"]
  },
  {
    id: 'resort-9',
    name: "Emerald Maldives Resort & Spa",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/EmeraldMaldivesResort&Spa/600/400`,
    q_despreocupacion: ["A"],
    q5: ["B","C"],
    q1: ["B"],
    q2: ["B"],
    q3: ["A"],
    q4: ["A"],
    'q4.1': ["A"],
    'q4.2': [],
    q9: ["B","C"],
    q11: ["B","D"],
    q_priorities: ["B", "G"]
  },
  {
    id: 'resort-10',
    name: "Hurawalhi Island Resort",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/HurawalhiIslandResort/600/400`,
    q_despreocupacion: ["B"],
    q5: ["A","B","C"],
    q1: ["A"],
    q2: ["A"],
    q3: ["A","B","C"],
    q4: ["A"],
    'q4.1': ["A"],
    'q4.2': [],
    q9: ["A","C"],
    q11: ["B","D"],
    q_priorities: ["A", "B", "C", "D", "H"]
  },
  {
    id: 'resort-11',
    name: "Centara Grand Machchafushi",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/CentaraGrandMachchafushi/600/400`,
    q_despreocupacion: ["B"],
    q5: ["B","C"],
    q1: ["A"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A","B"],
    'q4.1': ["A","B"],
    'q4.2': ["B"],
    q9: ["B","C"],
    q11: ["B","D"],
    q_priorities: ["A", "B", "D", "F", "G"]
  },
  {
    id: 'resort-12',
    name: "Barceló Whale Lagoon",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/BarcelóWhaleLagoon/600/400`,
    q_despreocupacion: ["B"],
    q5: ["B","C"],
    q1: ["A"],
    q2: ["B"],
    q3: ["A"],
    q4: ["A","B"],
    'q4.1': ["A","B"],
    'q4.2': ["B"],
    q9: ["A","C"],
    q11: ["B","D"],
    q_priorities: ["B", "D", "F", "H"]
  },
  {
    id: 'resort-13',
    name: "Outrigger Maldives Maafushivaru",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/OutriggerMaldivesMaafushivaru/600/400`,
    q_despreocupacion: ["B"],
    q5: ["B","C"],
    q1: ["A"],
    q2: ["B"],
    q3: ["A"],
    q4: ["A","B"],
    'q4.1': ["A","B"],
    'q4.2': ["B"],
    q9: ["B","C"],
    q11: ["B","D"],
    q_priorities: ["B", "D", "F", "G"]
  },
  {
    id: 'resort-14',
    name: "JA Manafaru",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/JAManafaru/600/400`,
    q_despreocupacion: ["B"],
    q5: ["B","C"],
    q1: ["B"],
    q2: ["A"],
    q3: ["A","B","C"],
    q4: ["A"],
    'q4.1': ["A"],
    'q4.2': [],
    q9: ["A","C"],
    q11: ["B","D"],
    q_priorities: ["A", "B", "H"]
  },
  {
    id: 'resort-15',
    name: "Pullman Maldives Maamutaa",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/PullmanMaldivesMaamutaa/600/400`,
    q_despreocupacion: ["B"],
    q5: ["A","B","C"],
    q1: ["B"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A"],
    'q4.1': ["A"],
    'q4.2': [],
    q9: ["A","C"],
    q11: ["C","D"],
    q_priorities: ["A", "B", "C", "H"]
  },
  {
    id: 'resort-16',
    name: "Six Senses Laamu",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/SixSensesLaamu/600/400`,
    q_despreocupacion: ["B"],
    q5: ["A","B","C"],
    q1: ["B"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A"],
    'q4.1': ["A"],
    'q4.2': [],
    q9: ["A","C"],
    q11: ["B","D"],
    q_priorities: ["A", "B", "C", "H"]
  },
  {
    id: 'resort-17',
    name: "InterContinental Maamunagau",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/InterContinentalMaamunagau/600/400`,
    q_despreocupacion: ["B"],
    q5: ["A","B","C"],
    q1: ["B"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A","B"],
    'q4.1': ["A","B"],
    'q4.2': ["A","B"],
    q9: ["B","C"],
    q11: ["B","D"],
    q_priorities: ["A", "B", "C", "F", "G"]
  },
  {
    id: 'resort-18',
    name: "Mövenpick Kuredhivaru",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/MövenpickKuredhivaru/600/400`,
    q_despreocupacion: ["B"],
    q5: ["A","B","C"],
    q1: ["B"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A"],
    'q4.1': ["A"],
    'q4.2': [],
    q9: ["A","C"],
    q11: ["B","D"],
    q_priorities: ["A", "B", "C", "H"]
  },
  {
    id: 'resort-19',
    name: "Lily Beach Resort & Spa",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/LilyBeachResort&Spa/600/400`,
    q_despreocupacion: ["B"],
    q5: ["B","C"],
    q1: ["B"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A","B"],
    'q4.1': ["A","B"],
    'q4.2': ["B"],
    q9: ["A","C"],
    q11: ["B","D"],
    q_priorities: ["A", "B", "F", "H"]
  },
  {
    id: 'resort-20',
    name: "Avani+ Fares Maldives",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/Avani+FaresMaldives/600/400`,
    q_despreocupacion: ["B"],
    q5: ["A","B","C"],
    q1: ["C"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A","B"],
    'q4.1': ["A","B"],
    'q4.2': ["A","B"],
    q9: ["B","C"],
    q11: ["B","D"],
    q_priorities: ["A", "B", "C", "E", "F", "G"]
  },
  {
    id: 'resort-21',
    name: "Kuramathi",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/Kuramathi/600/400`,
    q_despreocupacion: ["B"],
    q5: ["C"],
    q1: ["C"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A","B"],
    'q4.1': ["A","B"],
    'q4.2': ["B"],
    q9: ["A","C"],
    q11: ["A","D"],
    q_priorities: ["A", "B", "E", "F", "H"]
  },
  {
    id: 'resort-22',
    name: "Heritance Aarah",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/HeritanceAarah/600/400`,
    q_despreocupacion: ["B"],
    q5: ["B","C"],
    q1: ["C"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A","B"],
    'q4.1': ["A","B"],
    'q4.2': ["A"],
    q9: ["A","C"],
    q11: ["B","D"],
    q_priorities: ["A", "B", "E", "F", "H"]
  },
  {
    id: 'resort-23',
    name: "Sun Siyam Olhuveli",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/SunSiyamOlhuveli/600/400`,
    q_despreocupacion: ["B"],
    q5: ["B","C"],
    q1: ["C"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A","B"],
    'q4.1': ["A","B"],
    'q4.2': ["B"],
    q9: ["B","C"],
    q11: ["A","D"],
    q_priorities: ["A", "B", "E", "F", "G"]
  },
  {
    id: 'resort-24',
    name: "Dhigali Maldives",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/DhigaliMaldives/600/400`,
    q_despreocupacion: ["B"],
    q5: ["B","C"],
    q1: ["C"],
    q2: ["B"],
    q3: ["A","B","C"],
    q4: ["A","B"],
    'q4.1': ["A","B"],
    'q4.2': ["A"],
    q9: ["B","C"],
    q11: ["B","D"],
    q_priorities: ["A", "B", "E", "F", "G"]
  },
  {
    id: 'resort-25',
    name: "Siyam World Resort",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/SiyamWorldResort/600/400`,
    q_despreocupacion: ["B"],
    q5: ["B","C"],
    q1: ["C"],
    q2: ["B"],
    q3: ["A"],
    q4: ["A"],
    'q4.1': ["A"],
    'q4.2': [],
    q9: ["B","C"],
    q11: ["B","D"],
    q_priorities: ["B", "E", "G"]
  },
  {
    id: 'resort-26',
    name: "Conrad Maldives Rangali Island",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/ConradMaldivesRangaliIsland/600/400`,
    q_despreocupacion: ["B","C"],
    q5: ["A","B","C"],
    q1: ["C"],
    q2: ["A"],
    q3: ["A"],
    q4: ["A","B"],
    'q4.1': ["A","B"],
    'q4.2': ["B"],
    q9: ["B","C"],
    q11: ["B","D"],
    q_priorities: ["B", "C", "E", "F", "G"]
  },
  {
    id: 'resort-27',
    name: "Niyama Private Islands",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/NiyamaPrivateIslands/600/400`,
    q_despreocupacion: ["B","C"],
    q5: ["A","B","C"],
    q1: ["C"],
    q2: ["A"],
    q3: ["A"],
    q4: ["A"],
    'q4.1': ["A"],
    'q4.2': [],
    q9: ["A","C"],
    q11: ["B","D"],
    q_priorities: ["B", "C", "E", "H"]
  },
  {
    id: 'resort-28',
    name: "Anantara Veli Maldives",
    description: "Descripción pendiente. Pronto actualizaremos las características exactas de este resort.",
    imageUrl: `https://picsum.photos/seed/AnantaraVeliMaldives/600/400`,
    q_despreocupacion: ["B","C"],
    q5: ["A","B","C"],
    q1: ["A"],
    q2: ["A"],
    q3: ["A"],
    q4: ["A","B"],
    'q4.1': ["A","B"],
    'q4.2': ["C"],
    q9: ["A","C"],
    q11: ["A","D"],
    q_priorities: ["B", "C", "D", "F", "H"]
  }
];
