import { Resort } from './types';

// Fotos: biblioteca de medios de kakunitravels.com (versión -768x576 para móvil).
// Actualizado 08/07/2026: subidas y enlazadas las 5 que faltaban
//   (Emerald Faarufushi, Mövenpick Kuredhivaru, Heritance Aarah, Sun Siyam Olhuveli, Dhigali).
const IMG = 'https://kakunitravels.com/wp-content/uploads/2026/03/';
const IMG07 = 'https://kakunitravels.com/wp-content/uploads/2026/07/';

export const RESORTS: Resort[] = [
  {
    id: 'resort-0',
    name: "OBLU Select Lobigili",
    imageUrl: IMG + 'OBLU-SELECT-Lobigili-Full-Island-Aerial-02_800x600-768x576.webp',
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["B"],
    avistamiento_fauna: ["A","B"],
    logistica_fauna: ["A","B"],
    tipo_animal: ["C"],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["A","D"],
  },
  {
    id: 'resort-1',
    name: "Emerald Faarufushi Resort & Spa",
    imageUrl: IMG07 + 'maldivas-arrecife-turquesa-bungalows-agua-768x576.webp',
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-2',
    name: "OBLU Nature Helengeli",
    imageUrl: IMG + 'OBLU-NATURE-Helengeli-by-SENTIDO-Full-Island-Aerial_800x600-768x576.webp',
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["A","D"],
  },
  {
    id: 'resort-3',
    name: "Veligandu Maldives",
    imageUrl: IMG + 'veligandu_800x600-768x576.webp',
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A","B"],
    logistica_fauna: ["A","B"],
    tipo_animal: ["A","B"],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-4',
    name: "VARU by Atmosphere",
    imageUrl: IMG + 'varu_800x600-768x576.webp',
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["B"],
    avistamiento_fauna: ["A","B"],
    logistica_fauna: ["A","B"],
    tipo_animal: ["C"],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["A","D"],
  },
  {
    id: 'resort-5',
    name: "OBLU Select Sangeli",
    imageUrl: IMG + 'OBLU-SELECT-at-Sangeli-AERIAL-VIEW-Island-Aerial-02_800x600-768x576.webp',
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["A","D"],
  },
  {
    id: 'resort-6',
    name: "OZEN Life Maadhoo",
    imageUrl: IMG + 'ozen-life-madhoo_800x600-768x576.webp',
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["B"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A","C"],
    tipo_traslado: ["A","D"],
  },
  {
    id: 'resort-7',
    name: "RAAYA by Atmosphere",
    imageUrl: IMG + 'raaya_800x600-768x576.webp',
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["B"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-8',
    name: "Atmosphere Kanifushi",
    imageUrl: IMG + 'kanifushi_800x600-768x576.webp',
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["B"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A","B","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-9',
    name: "Emerald Maldives Resort & Spa",
    imageUrl: IMG + 'emerald_800x600-768x576.webp',
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["A"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-10',
    name: "Hurawalhi Island Resort",
    imageUrl: IMG + 'hurawalhi_800x600-768x576.webp',
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-11',
    name: "Centara Grand Machchafushi",
    imageUrl: IMG + 'machchanfushi_800x600-768x576.webp',
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A","B"],
    logistica_fauna: ["A","B"],
    tipo_animal: ["B"],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-12',
    name: "Melià Whale Lagoon",
    imageUrl: IMG + 'melia-whale-laagoon_800x600-768x576.webp',
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["B","C"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["A"],
    avistamiento_fauna: ["A","B"],
    logistica_fauna: ["A","B"],
    tipo_animal: ["B"],
    diseno_habitacion: ["A","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-13',
    name: "Outrigger Maldives Maafushivaru",
    imageUrl: IMG + 'outrigger-maldives-maafushivaru_800x600-768x576.webp',
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["A"],
    avistamiento_fauna: ["A","B"],
    logistica_fauna: ["A","B"],
    tipo_animal: ["B"],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-14',
    name: "JA Manafaru",
    imageUrl: IMG + 'jamanafaru_800x600-768x576.webp',
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-15',
    name: "Pullman Maldives Maamutaa",
    imageUrl: IMG + 'pullman_800x600-768x576.webp',
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A","C"],
    tipo_traslado: ["C","D"],
  },
  {
    id: 'resort-16',
    name: "Six Senses Laamu",
    imageUrl: IMG + 'six-senses-laamu_800x600-768x576.webp',
    nivel_despreocupacion: ["C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-17',
    name: "InterContinental Maamunagau",
    imageUrl: IMG + 'intercontinental_800x600-768x576.webp',
    nivel_despreocupacion: ["B","C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A","B"],
    logistica_fauna: ["A","B"],
    tipo_animal: ["A"],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-18',
    name: "Mövenpick Kuredhivaru",
    imageUrl: IMG07 + 'isla-resort-maldivas-atardecer-vista-aerea-768x576.webp',
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-19',
    name: "Lily Beach Resort & Spa",
    imageUrl: IMG + 'lily_800x600-768x576.webp',
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A","B"],
    logistica_fauna: ["A","B"],
    tipo_animal: ["B"],
    diseno_habitacion: ["A","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-20',
    name: "Avani+ Fares Maldives",
    imageUrl: IMG + 'avani_800x600-768x576.webp',
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["A","B","C"],
    atmosfera_isla: ["C"],
    experiencia_snorkel: ["A","B","C"],
    avistamiento_fauna: ["A","B"],
    logistica_fauna: ["A","B"],
    tipo_animal: ["A","B"],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-21',
    name: "Kuramathi",
    imageUrl: IMG + 'kuramathi_800x600-768x576.webp',
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["C"],
    atmosfera_isla: ["C"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A","B"],
    logistica_fauna: ["A","B"],
    tipo_animal: ["B"],
    diseno_habitacion: ["A","C"],
    tipo_traslado: ["A","D"],
  },
  {
    id: 'resort-22',
    name: "Heritance Aarah",
    imageUrl: IMG07 + 'isla-resort-heritance-aarah-maldivas-vista-aerea-768x576.webp',
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["C"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A","B"],
    logistica_fauna: ["A","B"],
    tipo_animal: ["A"],
    diseno_habitacion: ["A","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-23',
    name: "Sun Siyam Olhuveli",
    imageUrl: IMG07 + 'maldivas-bungalows-sobre-el-agua-vista-aerea-768x576.webp',
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["C"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A","B"],
    logistica_fauna: ["A","B"],
    tipo_animal: ["B"],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["A","D"],
  },
  {
    id: 'resort-24',
    name: "Dhigali Maldives",
    imageUrl: IMG07 + 'isla-maldivas-amanecer-dorado-bungalows-768x576.webp',
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["C"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A","B"],
    logistica_fauna: ["A","B"],
    tipo_animal: ["A"],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-25',
    name: "Siyam World Resort",
    imageUrl: IMG + 'siyam-world-maldives_800x600-768x576.webp',
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["C"],
    experiencia_snorkel: ["A"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-26',
    name: "Conrad Maldives Rangali Island",
    imageUrl: IMG + 'conrad_maldives_800x600-768x576.webp',
    nivel_despreocupacion: ["B","C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["C"],
    experiencia_snorkel: ["A"],
    avistamiento_fauna: ["A","B"],
    logistica_fauna: ["A","B"],
    tipo_animal: ["B"],
    diseno_habitacion: ["B","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-27',
    name: "Niyama Private Islands",
    imageUrl: IMG + 'niyama_800x600-768x576.webp',
    nivel_despreocupacion: ["B","C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["C"],
    experiencia_snorkel: ["A"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A","C"],
    tipo_traslado: ["B","D"],
  },
  {
    id: 'resort-28',
    name: "Anantara Veli Maldives",
    imageUrl: IMG + 'anantara-veli_800x600-768x576.webp',
    nivel_despreocupacion: ["B","C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["A"],
    avistamiento_fauna: ["A","B"],
    logistica_fauna: ["A","B"],
    tipo_animal: ["C"],
    diseno_habitacion: ["A","C"],
    tipo_traslado: ["A","D"],
  }
];
