import { Resort } from './types';

// ⚠️ ARCHIVO GENERADO AUTOMÁTICAMENTE — NO EDITAR A MANO.
// Se regenera en cada build desde Airtable: base LEADS > PROPIEDADES > choosen2025/2026.
// Para cambiar un resort, edítalo en Airtable. Generado el 2026-10-08T05:56:33.000Z.

export const RESORTS: Resort[] = [
  {
    id: 'rec1rYSM4QydKEp3E',
    name: "ATMOSPHERE KANIFUSHI",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/kanifushi_800x600-768x576.webp",
    franja: 1,
    bestSeller: true,
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["B"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A", "B", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'rec3VTTiocFBKuJKZ',
    name: "OBLU SELECT LOBIGILI",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/OBLU-SELECT-Lobigili-Full-Island-Aerial-02_800x600-768x576.webp",
    franja: 1,
    bestSeller: false,
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["B"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["C"],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["A", "D"],
  },
  {
    id: 'rec3bnzOlcAnPSUzV',
    name: "SUN SIYAM OLHUVELI",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/07/maldivas-bungalows-sobre-el-agua-vista-aerea-768x576.webp",
    franja: 1,
    bestSeller: false,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["B"],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["A", "D"],
  },
  {
    id: 'rec4TSlxnFjW3toCH',
    name: "LILY BEACH RESORT & SPA",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/lily_800x600-768x576.webp",
    franja: 3,
    bestSeller: false,
    nivel_despreocupacion: ["A", "B"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["B"],
    diseno_habitacion: ["A", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'rec5y0FsdCGO5F5IV',
    name: "OZEN LIFE MAADHOO",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/ozen-life-madhoo_800x600-768x576.webp",
    franja: 2,
    bestSeller: false,
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["B"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A", "C"],
    tipo_traslado: ["A", "D"],
  },
  {
    id: 'rec6tVSUUEhyWdw9l',
    name: "INTERCONTINENTAL MALDIVES",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/intercontinental_800x600-768x576.webp",
    franja: 4,
    bestSeller: false,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["A"],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'rec7XK0XErTj2IgWz',
    name: "VILLA NAUTICA",
    imageUrl: "https://image.hummingbird.travel/disk1/public/hotels/734/b9ee6dae-0dcd-4f38-ba11-cd323e6cdeb9.jpg",
    franja: 2,
    bestSeller: false,
    nivel_despreocupacion: ["A", "B", "C"],
    perfil_foodie: ["A", "B"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["B", "C"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["A"],
    diseno_habitacion: ["A", "C"],
    tipo_traslado: ["A", "D"],
  },
  {
    id: 'recAL3qs5jy0x9zQg',
    name: "NOVA MALDIVES",
    imageUrl: "https://image.hummingbird.travel/disk1/public/hotels/612/5666aa7a-5e93-48c4-9540-957c01d3d856.jpg",
    franja: 3,
    bestSeller: false,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["A", "B"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["B"],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["B", "C", "D"],
  },
  {
    id: 'recCOrjKEy6Qr4ICj',
    name: "OBLU SELECT SANGELI",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/OBLU-SELECT-at-Sangeli-AERIAL-VIEW-Island-Aerial-02_800x600-768x576.webp",
    franja: 1,
    bestSeller: false,
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["A", "D"],
  },
  {
    id: 'recCcSjep9foCeah6',
    name: "SIX SENSES LAAMU",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/six-senses-laamu_800x600-768x576.webp",
    franja: 4,
    bestSeller: false,
    nivel_despreocupacion: ["C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recFA7dIWtWFgPCkX',
    name: "EMERALD FAARUFUSHI RESORT & SPA",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/07/maldivas-arrecife-turquesa-bungalows-agua-768x576.webp",
    franja: 3,
    bestSeller: false,
    nivel_despreocupacion: ["A", "B"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recFhyEGwpwYIwWWy',
    name: "PULLMAN MALDIVES MAAMUTAA",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/pullman_800x600-768x576.webp",
    franja: 4,
    bestSeller: false,
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A", "C"],
    tipo_traslado: ["C", "D"],
  },
  {
    id: 'recOiFN0ckhZjHSc5',
    name: "Centara Grand Machchafushi",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/machchanfushi_800x600-768x576.webp",
    franja: 2,
    bestSeller: false,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["B"],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recPOKXsITUfTfeA7',
    name: "VARU BY ATMOSPHERE",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/varu_800x600-768x576.webp",
    franja: 1,
    bestSeller: false,
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["B"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["C"],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["A", "D"],
  },
  {
    id: 'recQ2d7G3HYqrTZWM',
    name: "KUREDHIVARU MALDIVES",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/07/isla-resort-maldivas-atardecer-vista-aerea-768x576.webp",
    franja: 4,
    bestSeller: false,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recRRXYXd4RVD0a5g',
    name: "HURAWALHI ISLAND RESORT",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/hurawalhi_800x600-768x576.webp",
    franja: 3,
    bestSeller: false,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recU4xQEFIaebym5O',
    name: "NIYAMA PRIVATE ISLANDS",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/niyama_800x600-768x576.webp",
    franja: 4,
    bestSeller: false,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["A"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recUGPzn9T3WF1RDx',
    name: "ANANEA MADIVARU MALDIVES",
    imageUrl: "https://image.hummingbird.travel/disk1/public/hotels/1117/70636480-a9e9-4d69-87fc-32482677527f.jpg",
    franja: 3,
    bestSeller: false,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["A"],
    diseno_habitacion: ["A", "B", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recZSARrT74s5hQ0x',
    name: "ANANTARA VELI MALDIVES RESORT",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/anantara-veli_800x600-768x576.webp",
    franja: 3,
    bestSeller: false,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["A"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["C"],
    diseno_habitacion: ["A", "C"],
    tipo_traslado: ["A", "D"],
  },
  {
    id: 'recb5Guvg7hu2N0JJ',
    name: "NIVA DHIGALI MALDIVES",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/07/isla-maldivas-amanecer-dorado-bungalows-768x576.webp",
    franja: 2,
    bestSeller: false,
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["A"],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recbgRk1g2WZRlTNa',
    name: "EMERALD MALDIVES RESORT & SPA",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/emerald_800x600-768x576.webp",
    franja: 2,
    bestSeller: true,
    nivel_despreocupacion: ["A", "B"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["A"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recdcSOMHpMYmwKzI',
    name: "KUDAFUSHI MALDIVES",
    imageUrl: "https://image.hummingbird.travel/disk1/public/hotels/20/bc725e1a-65e0-4c9f-b244-c782cf859631.jpg",
    franja: 2,
    bestSeller: false,
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A", "C"],
    tipo_traslado: ["B", "C", "D"],
  },
  {
    id: 'recePKDoi1GGE7UxF',
    name: "VELIGANDU MALDIVES RESORT ISLAND",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/veligandu_800x600-768x576.webp",
    franja: 2,
    bestSeller: true,
    nivel_despreocupacion: ["A", "B", "C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["A", "B"],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recfwEJIUZieIs9dd',
    name: "KANDIMA MALDIVES",
    imageUrl: "https://image.hummingbird.travel/disk1/public/hotels/44/3100d08c-3156-421b-8fbf-1c0d6653aded.jpg",
    franja: 2,
    bestSeller: false,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["A", "B"],
    atmosfera_isla: ["C"],
    experiencia_snorkel: ["A", "B"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["B", "C", "D"],
  },
  {
    id: 'recghwzPi5l2ZWwF8',
    name: "OBLU NATURE HELENGELI BY SENTIDO",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/OBLU-NATURE-Helengeli-by-SENTIDO-Full-Island-Aerial_800x600-768x576.webp",
    franja: 1,
    bestSeller: false,
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["A", "D"],
  },
  {
    id: 'recj6nhUqhzZarRar',
    name: "HERITANCE AARAH",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/07/isla-resort-heritance-aarah-maldivas-vista-aerea-768x576.webp",
    franja: 4,
    bestSeller: false,
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["A"],
    diseno_habitacion: ["A", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recmK2irt6Z1Gnq3h',
    name: "RAAYA BY ATMOSPHERE",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/raaya_800x600-768x576.webp",
    franja: 1,
    bestSeller: false,
    nivel_despreocupacion: ["A"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["B"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recpbVDJHGUfGVAUd',
    name: "NH Collection Reethi",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/10/nh-collection-reethi-maldivas-vista-aerea_800x600-768x576.webp",
    franja: 3,
    bestSeller: false,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["A", "B"],
    experiencia_snorkel: ["B", "C"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["A"],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["B", "C", "D"],
  },
  {
    id: 'recsdc9zcL3nOksNi',
    name: "SIYAM WORLD RESORT",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/siyam-world-maldives_800x600-768x576.webp",
    franja: 2,
    bestSeller: false,
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["C"],
    experiencia_snorkel: ["A"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recsngmvC4SnWHgFN',
    name: "AVANI & FARES",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/avani_800x600-768x576.webp",
    franja: 3,
    bestSeller: false,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["A", "B"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["A", "B", "C"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["A", "B"],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recuVy5QyKSBCUZ8I',
    name: "JA MANAFARU",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/jamanafaru_800x600-768x576.webp",
    franja: 3,
    bestSeller: false,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A"],
    logistica_fauna: ["A"],
    tipo_animal: [],
    diseno_habitacion: ["A", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recvqeyVxXFglvl7P',
    name: "CONRAD MALDIVES RANGALI",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/conrad_maldives_800x600-768x576.webp",
    franja: 4,
    bestSeller: true,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["A"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["B"],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'recxTKjR5fh8OZfpj',
    name: "NIVA KURAMATHI MALDIVES",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/kuramathi_800x600-768x576.webp",
    franja: 1,
    bestSeller: false,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["A", "B"],
    atmosfera_isla: ["B"],
    experiencia_snorkel: ["C"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["B"],
    diseno_habitacion: ["A", "C"],
    tipo_traslado: ["A", "D"],
  },
  {
    id: 'recyI7KW5iR3l1iMp',
    name: "OUTRIGGER MALDIVES MAAFUSHIVARU RESORT",
    imageUrl: "https://kakunitravels.com/wp-content/uploads/2026/03/outrigger-maldives-maafushivaru_800x600-768x576.webp",
    franja: 3,
    bestSeller: false,
    nivel_despreocupacion: ["B", "C"],
    perfil_foodie: ["A"],
    atmosfera_isla: ["A"],
    experiencia_snorkel: ["A"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["B"],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["B", "D"],
  },
  {
    id: 'reczXMq3NlAkwzSJl',
    name: "OBLU XPERIENCE AILAFUSHI",
    imageUrl: "https://image.hummingbird.travel/disk1/public/hotels/619/5ce5dffd-d0a4-4cfc-b0d1-1f9f45d25c84.jpg",
    franja: 1,
    bestSeller: false,
    nivel_despreocupacion: ["B"],
    perfil_foodie: ["B"],
    atmosfera_isla: ["C"],
    experiencia_snorkel: ["B"],
    avistamiento_fauna: ["A", "B"],
    logistica_fauna: ["A", "B"],
    tipo_animal: ["A", "C"],
    diseno_habitacion: ["B", "C"],
    tipo_traslado: ["A", "D"],
  },
];
